import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Italiana } from "next/font/google";
import SmoothScroll from "../components/ui/SmoothScroll";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: '--font-montserrat',
  weight: "400",
});

const italiana = Italiana({
  subsets: ["latin"],
  variable: '--font-italiana',
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${italiana.variable}`}>
      <body className="dark">
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
